### ISSUE TITLE
Method not found: 'Void Umbraco.Core.Security.BackOfficeUserStore..ctor

### ISSUE THREAD

**Issue by timeverts** [cleversolutions/U2#1]
I am getting a 'Method not found' error when attempting to use this package.

I've installed the package via nuget and added the example code to the `ConfigureUmbracoAuthentication` in the `App_Start/UmbracoCustomOwinStartup.cs` class, like so:

```
        /// <summary>
        /// Configures the back office authentication for Umbraco
        /// </summary>
        /// <param name="app"></param>
        protected override void ConfigureUmbracoAuthentication(IAppBuilder app)
        {
            app
                .UseUmbracoBackOfficeCookieAuthentication(UmbracoContextAccessor, RuntimeState, Services.UserService,
                    GlobalSettings, UmbracoSettings.Security, PipelineStage.Authenticate)
                .UseUmbracoBackOfficeExternalCookieAuthentication(UmbracoContextAccessor, RuntimeState, GlobalSettings,
                    PipelineStage.Authenticate)
                .UseUmbracoPreviewAuthentication(UmbracoContextAccessor, RuntimeState, GlobalSettings,
                    UmbracoSettings.Security, PipelineStage.Authorize);

            /* 
             * Configure external logins for the back office:
             * 
             * Depending on the authentication sources you would like to enable, you will need to install 
             * certain Nuget packages. 
             * 
             * For Google auth:					Install-Package UmbracoCms.IdentityExtensions.Google
             * For Facebook auth:					Install-Package UmbracoCms.IdentityExtensions.Facebook
             * For Microsoft auth:					Install-Package UmbracoCms.IdentityExtensions.Microsoft
             * For Azure ActiveDirectory auth:		Install-Package UmbracoCms.IdentityExtensions.AzureActiveDirectory
             * 
             * There are many more providers such as Twitter, Yahoo, ActiveDirectory, etc... most information can
             * be found here: http://www.asp.net/web-api/overview/security/external-authentication-services
             * 
             * For sample code on using external providers with the Umbraco back office, install one of the 
             * packages listed above to review it's code samples 
             *  
             */

            /*
             * To configure a simple auth token server for the back office:
             *             
             * By default the CORS policy is to allow all requests
             * 
             *      app.UseUmbracoBackOfficeTokenAuth(new BackOfficeAuthServerProviderOptions());
             *      
             * If you want to have a custom CORS policy for the token server you can provide
             * a custom CORS policy, example: 
             * 
             *      app.UseUmbracoBackOfficeTokenAuth(
             *          new BackOfficeAuthServerProviderOptions()
             *              {
             *             		//Modify the CorsPolicy as required
             *                  CorsPolicy = new CorsPolicy()
             *                  {
             *                      AllowAnyHeader = true,
             *                      AllowAnyMethod = true,
             *                      Origins = { "http://mywebsite.com" }                
             *                  }
             *              });
             */

            // Enable token authentication, must be called before ConfigureUmbracoAuthentication
            app.UseUmbracoBackOfficeTokenAuth(new BackOfficeAuthServerProviderOptions());

            // To enable 2FA use the two factor sign in cookie and configure the usermanager to use U2BackOfficeUserManager
            app.UseTwoFactorSignInCookie(Umbraco.Core.Constants.Security.BackOfficeTwoFactorAuthenticationType,
                TimeSpan.FromMinutes(20));

            UmbracoMapper umbracoMapper = Umbraco.Core.Composing.Current.Mapper;
            app.ConfigureUserManagerForUmbracoBackOffice<U2BackOfficeUserManager, BackOfficeIdentityUser>(
                Umbraco.Web.Composing.Current.RuntimeState,
                GlobalSettings,
                (options, context) =>
                {
                    var membershipProvider = MembershipProviderExtensions.GetUsersMembershipProvider()
                        .AsUmbracoMembershipProvider();
                    var userManager = U2BackOfficeUserManager.Create(options,
                        Services.UserService,
                        Services.MemberTypeService,
                        Services.EntityService,
                        Services.ExternalLoginService,
                        membershipProvider,
                        GlobalSettings,
                        umbracoMapper);
                    return userManager;
                });

            // Must call the base implementation to configure the default back office authentication config.
            base.ConfigureUmbracoAuthentication(app);
        }
```

I've then set the custom owin startup class in Web.config and built my solution. 
Upon loading my site I encounter the following error:

```
Method not found: 'Void Umbraco.Core.Security.BackOfficeUserStore..ctor(Umbraco.Core.Services.IUserService, Umbraco.Core.Services.IMemberTypeService, Umbraco.Core.Services.IEntityService, Umbraco.Core.Services.IExternalLoginService, Umbraco.Core.Configuration.IGlobalSettings, Umbraco.Core.Security.MembershipProviderBase, Umbraco.Core.Mapping.UmbracoMapper, Umbraco.Core.Cache.AppCaches)'.
```

**Description:** An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

**Exception Details:** 
```
System.MissingMethodException: Method not found: 'Void Umbraco.Core.Security.BackOfficeUserStore..ctor(Umbraco.Core.Services.IUserService, Umbraco.Core.Services.IMemberTypeService, Umbraco.Core.Services.IEntityService, Umbraco.Core.Services.IExternalLoginService, Umbraco.Core.Configuration.IGlobalSettings, Umbraco.Core.Security.MembershipProviderBase, Umbraco.Core.Mapping.UmbracoMapper, Umbraco.Core.Cache.AppCaches)'.
```

The exception is being triggered from the `var userManager = U2BackOfficeUserManager.Create(options,...` line.

I'm running Umbraco 8.3.0.

**Comment by cleversolutions** [comment]
Hi @timeverts, I've actually only tested this on Umbraco 8.13.0. I'll try out your Owin startup in an 8.13 site to verify it works there.

**Comment by cleversolutions** [comment]
Yes, it works great on 8.13. Maybe double check your using statements
```
using Microsoft.Owin;
using Owin;
using Umbraco.Web;
using Umbraco.Core.Mapping;
using Umbraco.Web.Security;
using U2.Middleware;
using Umbraco.Core.Models.Identity;
using Umbraco.Core.Security;
using System;
using Umbraco.IdentityExtensions;
using YourSitesAssembly;
```
If those are all the same (except for the last one) I think you may need to upgrade to a later version of Umbraco 8 (and I need to update the min version in my package). Luckily Umbraco 8 upgrades are relatively painless. I'm migrating a bunch of Umbraco 7 sites right now, the standard course of action is to migrate them to 8.5.5 first, then upgrade to 8.13. I've not run into a single problem with the 8.5.5 to 8.13 upgrades.

**Comment by cleversolutions** [comment]
I can confirm it doesn't work on 8.5.5 either.

**Comment by cleversolutions** [comment]
It works in v8.12 and above. I'll update the package dependencies. 8.12 deprecated the BackOfficeUserStore constructor used in previous version of 8 and introduced a new one.

**Comment by timeverts** [comment]
@cleversolutions, thanks for looking into this so soon!

I haven't seen the inner code and how it all works, but I was wondering whether it might be possible to make it backwards compatible by conditionally calling the suitable method depending on which version of Umbraco 8 is installed?

FYI: You should be able to retrieve the version installed using `umbraco.GlobalSettings.ConfigurationStatus` (which simply retrieves the appSettings property), or using `VersionMajor`, `VersionMinor` or `VersionPatch` in `umbraco.GlobalSettings`.

What do you think?

**Comment by timeverts** [comment]
> @cleversolutions, thanks for looking into this so soon!
> 
> I haven't seen the inner code and how it all works, but I was wondering whether it might be possible to make it backwards compatible by conditionally calling the suitable method depending on which version of Umbraco 8 is installed?
> 
> FYI: You should be able to retrieve the version installed using `umbraco.GlobalSettings.ConfigurationStatus` (which simply retrieves the appSettings property), or using `VersionMajor`, `VersionMinor` or `VersionPatch` in `umbraco.GlobalSettings`.
> 
> What do you think?

Actually, I guess this all depends on whether the method is actually just deprecated in 8.12 or has been removed. I'm not sure if it would compile with that type of fallback if the new method doesn't exist or vice-versa.

**Comment by cleversolutions** [comment]
@timeverts I was on the fence about leaving this as is, or supporting older versions of Umbraco 8. 8.11 is a pretty high bar, and it is simply deprecated, not yet removed. I should be able to use the old constructor and ignore the warning. I suspect it's deprecated in 8, but won't be removed until 9. In either case I will cut a version of the package that works on 8.1.1 up, and when I have to, I'll switch back to the new constructor and a later version of the package will require 8.12 up (or 9 if that's when the change happens).

**Comment by cleversolutions** [comment]
@timeverts try version 1.0.2 of the package, I've tested it on 8.1.1 and 8.13 and it works on both, so I can assume it works on everything in between.
