### ISSUE TITLE
Need to trigger table refresh when disabling 2FA

### ISSUE THREAD

**Issue by timeverts** [cleversolutions/U2#4]
The table at the bottom of the 'Two Factor Authentication' tab needs to be refreshed when a user disables their 2FA.

To reproduce:
1. Log in to the backoffice
2. Enable 2FA (by following the instructions and entering the code from authenticator app)
3. Log out of backoffice
4. Log back into backoffice
5. Enter 2FA code
6. Visit the 'Two Step Authentication' tab
6. Click 'Disable two step verification' button
7. Table at the bottom of the tab still shows my user as having 2FA enabled

It will certainly update once the page is refreshed, but perhaps it should update immediately.

**Comment by cleversolutions** [comment]
Thanks Tim. Good catch. I'll see if I can find time this weekend to fix this.

**Comment by timeverts** [comment]
@cleversolutions, thanks so much for making all these usability fixes. Any ETA on when these latest batch of fixes (in version 1.1.1-alpha) might be up on Nuget?

**Comment by cleversolutions** [comment]
Thanks for the reminder @timeverts, I'll try to push them out tonight.

**Comment by timeverts** [comment]
> Thanks for the reminder @timeverts, I'll try to push them out tonight.

@cleversolutions, you're obviously as busy as I am! 

This week I'm doing some maintenance on the sites that use this package and would love install the updated version as part of that maintenance cycle. Any chance you might be able to do this in the next couple of days?
