### ISSUE TITLE
'Two Factor Authentication' dashboard still 'dirty' after entering valid code

### ISSUE THREAD

**Issue by timeverts** [cleversolutions/U2#5]
The 'Two Factor Authentication' dashboard is still considered 'dirty' after entering a valid code and enabling 2FA. This means that when trying to navigate away from the dashboard Umbraco displays a message about unsaved changes being present.

![image](https://user-images.githubusercontent.com/15150632/130003799-abef2e73-026f-4ac6-881c-78cfe4ab3bcc.png)

I think what you have do is add a `no-dirty-check` attribute on the code entry input element. See [this](https://our.umbraco.com/forum/umbraco-8/98277-how-to-stop-you-have-unsaved-changes-message) post.

**Comment by cleversolutions** [comment]
Thanks for the tip @timeverts, that was bugging me too.
