### ISSUE TITLE
`TypeError: usersResource.getUsers is not a function` in Umbraco 8.3

### ISSUE THREAD

**Issue by timeverts** [cleversolutions/U2#6]
Hi,

I am testing on Umbraco 8.3 and the majority of the functionality works fine which is fabulous!

However, one thing that does not work is the generation of the table at the bottom of the dashboard that lists the current users with 2FA enabled.

In Umbraco 8.3 I get a JavaScript error:
```javascript
angular.js?cdv=1969185542:15536 TypeError: usersResource.getUsers is not a function
    at managementdashboard.controller.js?cdv=1969185542:38
    at processQueue (angular.js?cdv=1969185542:17914)
    at angular.js?cdv=1969185542:17962
    at Scope.$digest (angular.js?cdv=1969185542:19075)
    at Scope.$apply (angular.js?cdv=1969185542:19463)
    at done (angular.js?cdv=1969185542:13312)
    at completeRequest (angular.js?cdv=1969185542:13569)
    at XMLHttpRequest.requestLoaded (angular.js?cdv=1969185542:13474) "Possibly unhandled rejection: {}"
```

The problem lies in the call made to `usersResource.getUsers` from within `managementdashboardcontroller.js` on line 35:

```javascript
        var getEnabledUserSettings = function () {
            $scope.isLoading = true;
            twoFactorService.getEnabledUserSettings().then(function (response) {
                usersResource.getUsers(response.data).then(function (userData) {
                    $scope.users = userData;
                    $scope.isLoading = false;
                });
            });
        };
```

I inspected the `usersResource` object and it has a `getUser(usedId)` method in Umbraco 8.3 but no `getUsers(userIds)` method. So a later version of Umbraco must have added the `getUsers(userIds)` method (e.g. I have a 8.10.2 install which is working fine with the existing JS). 

So perhaps to make the JS backwards compatible (as you kindly have done with the library itself via #1), you could edit the JS and implement a check whether the `getUsers` method is defined (E.g. `typeof usersResource.getUsers === 'function'`) . If it _is_ defined, then fetch the users as you are now. If it's not defined, then fetch the users one-by-one using the `getUser(userId)` method.

If you haven't got an Umbraco 8.3 instance handy and want me to test the update for you, I'm happy to do so. 

Thanks so much for all your work.

**Comment by cleversolutions** [comment]
Thanks Tim. Please do test this out on 8.3 and let me know how it works.
